version: '3.7'

services:
    python:
        build: .
        stdin_open: true
        tty: true
        command: /bin/sh -c "while sleep 1000; do :; done"
        volumes:
            - ./src:/workspace
